"""empty message

Revision ID: 1558cfd804c6
Revises: 68ddb8bd4909
Create Date: 2021-04-14 15:57:31.130540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1558cfd804c6'
down_revision = '68ddb8bd4909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Announcement', sa.Column('subject', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Announcement', 'subject')
    # ### end Alembic commands ###
