"""empty message

Revision ID: 4f08b662f2ba
Revises: 
Create Date: 2021-03-26 15:41:04.120970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f08b662f2ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Message')
    op.drop_table('Admin')
    op.drop_table('Instructor')
    op.drop_table('Assignment')
    op.drop_table('File')
    op.drop_table('Student')
    op.drop_table('Module')
    op.drop_table('Course')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('userType', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hasAccess', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='User_pkey'),
    sa.UniqueConstraint('email', name='User_email_key')
    )
    op.create_table('Course',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Course_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('instructor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['Instructor.id'], name='Course_instructor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Course_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Module',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Module_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Course.id'], name='Module_course_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Module_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Student',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Student_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Student_pkey'),
    sa.UniqueConstraint('email', name='Student_email_key')
    )
    op.create_table('File',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"File_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Assignment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Assignment_id'], ['Assignment.id'], name='File_Assignment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='File_pkey')
    )
    op.create_table('Assignment',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Assignment_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['Module.id'], name='Assignment_module_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Assignment_pkey')
    )
    op.create_table('Instructor',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Instructor_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Instructor_pkey'),
    sa.UniqueConstraint('email', name='Instructor_email_key')
    )
    op.create_table('Admin',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Admin_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Admin_pkey'),
    sa.UniqueConstraint('email', name='Admin_email_key')
    )
    op.create_table('Message',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Message_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Message_pkey')
    )
    # ### end Alembic commands ###
