"""empty message

Revision ID: 53dd984b1db1
Revises: dfffc11bb07f
Create Date: 2021-04-14 16:01:03.535905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53dd984b1db1'
down_revision = 'dfffc11bb07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Announcement', sa.Column('subject', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Announcement', 'subject')
    # ### end Alembic commands ###
