"""empty message

Revision ID: 58cffccd4257
Revises: 9e5c44bc2fd2
Create Date: 2021-03-28 18:39:41.824355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58cffccd4257'
down_revision = '9e5c44bc2fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    
    pass

    # op.create_table('User',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('email', sa.String(length=100), nullable=True),
    # sa.Column('password', sa.String(length=100), nullable=True),
    # sa.Column('name', sa.String(length=1000), nullable=True),
    # sa.Column('userType', sa.String(length=100), nullable=True),
    # sa.Column('hasAccess', sa.Boolean(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email')
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
