"""empty message

Revision ID: 8a5e2338a7a4
Revises: 9112d6b27369
Create Date: 2021-04-10 17:31:56.239062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5e2338a7a4'
down_revision = '9112d6b27369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('adminId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adminId'], ['Admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserOrganizations',
    sa.Column('organizationId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('organizationId', 'userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserOrganizations')
    op.drop_table('Organization')
    # ### end Alembic commands ###
