"""empty message

Revision ID: af1b8b0fa3ab
Revises: a3977a77333d
Create Date: 2021-04-14 15:58:07.696785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af1b8b0fa3ab'
down_revision = 'a3977a77333d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Announcement', sa.Column('subject', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Announcement', 'subject')
    # ### end Alembic commands ###
