"""empty message

Revision ID: ba06bbe34655
Revises: 58ef29a3b40f
Create Date: 2021-04-15 13:19:32.518429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba06bbe34655'
down_revision = '58ef29a3b40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assignment', sa.Column('courseId', sa.Integer(), nullable=False))
    op.add_column('Assignment', sa.Column('description', sa.String(length=1000), nullable=True))
    op.create_foreign_key(None, 'Assignment', 'Course', ['courseId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Assignment', type_='foreignkey')
    op.drop_column('Assignment', 'description')
    op.drop_column('Assignment', 'courseId')
    # ### end Alembic commands ###
