"""empty message

Revision ID: c2814f5aeca7
Revises: 53dd984b1db1
Create Date: 2021-04-15 13:18:06.645740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2814f5aeca7'
down_revision = '53dd984b1db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assignment', sa.Column('courseId', sa.Integer(), nullable=False))
    op.add_column('Assignment', sa.Column('description', sa.String(length=1000), nullable=True))
    op.create_foreign_key(None, 'Assignment', 'Course', ['courseId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Assignment', type_='foreignkey')
    op.drop_column('Assignment', 'description')
    op.drop_column('Assignment', 'courseId')
    # ### end Alembic commands ###
