"""empty message

Revision ID: f06753c7c19b
Revises: 336d133fed46
Create Date: 2021-04-10 17:46:20.643371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06753c7c19b'
down_revision = '336d133fed46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('userType', sa.String(length=100), nullable=True),
    sa.Column('hasAccess', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Instructor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(length=100), nullable=False),
    sa.Column('senderId', sa.Integer(), nullable=True),
    sa.Column('recipientId', sa.Integer(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.Column('isRead', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recipientId'], ['User.id'], ondelete='set null'),
    sa.ForeignKeyConstraint(['senderId'], ['User.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('instructorId', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('semester', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['instructorId'], ['Instructor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('adminId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adminId'], ['Admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('StudentCourses',
    sa.Column('courseId', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courseId'], ['Course.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['studentId'], ['Student.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('courseId', 'studentId')
    )
    op.create_table('UserOrganizations',
    sa.Column('organizationId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('organizationId', 'userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserOrganizations')
    op.drop_table('StudentCourses')
    op.drop_table('Organization')
    op.drop_table('Course')
    op.drop_table('Student')
    op.drop_table('Message')
    op.drop_table('Instructor')
    op.drop_table('Admin')
    op.drop_table('User')
    # ### end Alembic commands ###
