"""empty message

Revision ID: f34e538700ea
Revises: 4797ab434ab1
Create Date: 2021-04-14 13:43:35.266334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34e538700ea'
down_revision = '4797ab434ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('StudentCourses', sa.Column('grade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('StudentCourses', 'grade')
    # ### end Alembic commands ###
